name: Auto version bump

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - 'package.json'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-node:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: staging
    #container: node:16

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
          
      - name: 'cat package.json'
        run: cat ./package.json | grep "version"

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        #env:
          #GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag-prefix: 'v'
          major-wording: 'major-version'
          minor-wording: 'minor-version'
          patch-wording: 'patch-version'
          default: 'patch' 

      - name: 'cat package.json'
        run: cat ./package.json | grep "version"
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
